pipeline_cfg: /home/danielbinschmid/melddpm/code/configs/dm/cond_medley_v0/model/pipeline.yaml
out: /home/danielbinschmid/melddpm/data/logging/inference_out/cond_medley
n_samples_per_category_for_uniform_inference: 8
device: cuda:0
max_bs: 32
num_steps: 200
sampler_type: dpm
mirror_test_distribution: true