vocoder_cfg: "./vocoder.yaml"
vocoder_weights: "/home/danielbinschmid/melddpm/data/models/pretrained_opensource/musicldm_hifigan/hifigan-ckpt(only generator).ckpt"
unet_cfg: "./unet.yaml"
weights: "/home/danielbinschmid/melddpm/data/models/good_checkpoints/moises_guitar_v1/checkpoints/431.pth"
melddpm_cfg: "./melddpm.yaml"
original_base_path: "./"