attn_res:
- 8
channel_mults:
- 1
- 2
- 4
- 8
conditioning_mechanism: unconditional
conv_resample: true
dropout: 0.0
image_size: null
in_channel: 1
inner_channel: 64
num_head_channels: -1
num_heads: 1
num_heads_upsample: -1
out_channel: 1
res_blocks: 2
resblock_updown: true
use_checkpoint: false
use_fp16: false
use_new_attention_order: false
use_scale_shift_norm: true
