num_mels: 64
resblock_dilation_sizes:
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
resblock_kernel_sizes:
- 3
- 7
- 11
upsample_initial_channel: 1024
upsample_kernel_sizes:
- 16
- 16
- 8
- 4
- 4
upsample_rates:
- 5
- 4
- 2
- 2
- 2