cls_embedding_dim: 4
frame_size: 297
frequency_max: 8000.0
frequency_min: 0.0
hop_size: 160
mel_max_cfg_path: /home/danielbinschmid/melddpm/code/configs/medley_solos_db/mel_max.json
mel_min_cfg_path: /home/danielbinschmid/melddpm/code/configs/medley_solos_db/mel_min.json
n_categories: 0
nfft: 1024
sample_rate: 16000
mel_size: 64
