vocoder_cfg: "./vocoder.yaml"
vocoder_weights: "/home/danielbinschmid/audio-diffusion-training/data/hifigan/hifigan-ckpt(only generator).ckpt"
unet_cfg: "./unet.yaml"
weights: "/home/danielbinschmid/audio-diffusion-training/data/melddpm_v1/2024-12-03.pth"
melddpm_cfg: "./melddpm.yaml"
original_base_path: "./"